## YMreleaseBot configuration

ymreleasebot:
  name: 'xerxes-assistant'
  count_replicas: 1
  image: 'docker-ym.nexus.yamoney.ru/yamoney/xerxes-assistant'
  tag: <value>
  mysql:
    name: mysql
    port:
      name: mysql-client
      value: 3306
    ip: 10.200.51.2
  logging:
    configmap_name: 'log-config-ymreleasebot-assistant'
  resources:
    requests:
      memory: 128Mi
      cpu: '100m'
    limits:
      memory: 512Mi
      cpu: '200m'
  secrets:
    telegram:
      name: 'telegram'
      value: <value>
    mysql:
      name: 'mysql'
      pass: <value>
      user: <value>
    jira:
      name: 'jira'
      pass: <value>
      user: <value>
    exchange:
      name: 'exchange'
      pass: <value>
      user: <value>

