---
## YMreleaseBot configuration

releasebot:
  name: 'releasebot-assistant'
  app_type: 'python'
  app_name: 'releasebot'
  kafka_log_topic: 'yamoney_python_ymreleasebot'
  count_replicas: 1
  image: 'docker-ym.nexus.yamoney.ru/yamoney/releasebot-assistant'
  tag: 'latest'
  mysql:
    name: mysql
    port:
      name: mysql-client
      value: 3306
    ip: 10.200.51.2
  logging:
    configmap_name: 'log-config-releasebot-assistant'
  resources:
    requests:
      memory: 128Mi
      cpu: '100m'
    limits:
      memory: 512Mi
      cpu: '200m'
