{{ $conf := .Values.ymreleasebot }}
apiVersion: v1
data:
  pass: {{ $conf.secrets.pg.pass }}
  user:  {{ $conf.secrets.pg.user }}
kind: Secret
metadata:
  name: {{ $conf.secrets.pg.name }}
type: Opaque
